### ISSUE TITLE
Guides skip blank lines

### ISSUE THREAD

**Issue by dblock247** [spywhere/vscode-guides#1]
If i have a code bracket with blank lines in it for code separation and readability the guides lines have holes in them. I did not see an option to span across blank lines. Can you please add that. Also explain what rulers are. 

besides that. Great Extension

**Comment by spywhere** [comment]
The skipped guides on blank lines are expectable due to the limitation of the extension API. The guide is create by inserting an outline border at the character position so in order to show a guide, characters are required on those lines.

For the ruler, it's simply a static guide on particular character length (mostly 80). These are use to indicate a long line (as to conform the code guideline of character limits) or just a visual guide line in some cases.

**Comment by spywhere** [comment]
Reopened for the experiment with a new potential API introduced in Visual Studio Code v1.3.0

**Comment by pankajpatel** [comment]
Hello, any update on this issue?

**Comment by spywhere** [comment]
Sadly no. Although they provide the CSS's `after` and `before` into the decorators, there is not enough settings to make this happen at this moment.

**Comment by pankajpatel** [comment]
The internal guides are shown on the editor, you can take hint from there.

**Comment by spywhere** [comment]
After tinkering with CSS's `after` and `before` provided by VSCode, unfortunately this issue, though highly wish comes true, cannot be implemented without a proper VSCode rendering API.

To add more details, @pankajpatel solution is not possible due to the way extension cannot directly set particular CSS attributes. Another solution is to set a decoration with an offset which ends up cluttering on the beginning of the empty line, hence the solution is failed.

This issue will be close until VSCode has finally provide an extension a way to render a line on an empty line.
