### ISSUE TITLE
Can Guides or the default editor change location of the expansion buttons? And Active Guide styling doesn't seem to work for me. 

### ISSUE THREAD

**Issue by jcklpe** [spywhere/vscode-guides#28]
- [x ] I have search [open issues](https://github.com/spywhere/vscode-guides/issues) for duplicate issues
- [x ] I have search [close issues](https://github.com/spywhere/vscode-guides/issues?q=is%3Aissue+is%3Aclosed) for potential fixes
- Guides Version:  0.9.1
- VSCode Version:  1.2.1
- OS Version: Windows 10

Here's a peek at what my editor looks like: 
![image](https://user-images.githubusercontent.com/9451726/38380168-94ca5ca4-38c8-11e8-94c0-0ebe6db18d05.png)

Is it possible to have the little expanding boxes rendered next to the indent they're at instead at the edge of the screen?

I also don't see the active guide styling mentioned in the settings. It is turned on though. That should mean whatever bracket I'm in get's styled a certain way right?

**Comment by spywhere** [comment]
Unfortunately, extension cannot alter or modify the default folding box due to the API limitation. On the topic of active guides, it only applied to the indentation guide lines (not the backgrounds) hence it does not change any background colour. Though such a feature is surely possible, it would be available on the next major release (which already under development).
