### ISSUE TITLE
Working on a several line file causes very bad input lag

### ISSUE THREAD

**Issue by Tyriar** [spywhere/vscode-guides#6]
Here is a slice of a Chromium timeline of me typing around 15 characters in https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js

![image](https://cloud.githubusercontent.com/assets/2193314/15953106/f21ffff2-2e7b-11e6-9497-0a2be25fe77d.png)

Might not be worth fixing this is vscode's getting native guides though.

**Comment by spywhere** [comment]
That can be expected to me since Guides always update all indentation guides in the file. It would be a great addition to the VSCode API to get a range of visible lines on the editor though (I will file this issue for sure).

In the mean time, you can adjust the update interval (`guides.updateDelay`) to be longer. This should help reduce a lag due to multiple event fired.

**Comment by spywhere** [comment]
Guides v0.4.4 should reduce the lag in this issue by a lot since Guides no longer update the indentation guides upon appending text to the document. However, there are still a lag when enter a lot of new lines.

I will leave issue open as the extension still has rooms to improve on the performance side which I already got a plan for it.

**Comment by Jet-Set-Willy** [comment]
It might be a good idea to add a warning about this to the readme.

It makes vscode virtually unusable for me when I have files that are >20000 lines long.

It took me a while to figure out that it was Guides causing the problem.

**Comment by spywhere** [comment]
Thanks for reassuring the issue, @Jet-Set-Willy. The maximum line limitation is definitely on the plan, I aim for completing this feature (along with a few more) this weekends if possible.

**Comment by spywhere** [comment]
Rendering boundary limit has been implemented in v0.9.0. This should solve most of the performance issues so far. Feel free to open it if there is a significant performance issue while I'm working on a new processing / rendering engine to improve the performance even more.
